### ISSUE TITLE
During setup the account I cannot log to WIFI network

### ISSUE THREAD

**Issue by mirek190** [elementary/initial-setup#181] opened 2023-12-13 23:07 UTC
### What Happened?

As I said - During setup the account I cannot log to WIFI network
 I choose and click my wifi network to connect - getting window to input my password - click ok - and I not connecting to wifi.
I can connect to wifi in the fist stage ( installation from the usb stick ) and aftr login in too account after installation.  

Video to explain the problem
[https://mega.nz/file/UUgmSKiA#P25CwcUy0zwWNzQxJsa2p_uazJRLGvQXX_U8MoLI1v8](url)

### Steps to Reproduce

1. Install sytem
2. reboot
3. remove usb stick
4. second stage of installation - account setup. 
5. I choose and click my wifi network to connect - getting window to input my password - click ok - and I not connecting to wifi.
 

### Expected Behavior

Should connect?

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-12-14 00:55
Duplicate of https://github.com/elementary/greeter/issues/615

**Closed by lenemter** 2023-12-14 00:55 UTC
