### ISSUE TITLE
i idk how tofix the size

### ISSUE THREAD

**Issue by yarik303** [elementary/initial-setup#137] opened 2022-01-21 16:25 UTC
### What Happened?

![image](https://user-images.githubusercontent.com/75032600/150562897-b5e4387d-6d59-45d8-b703-b04b31cac1b6.png)
LITTERALLY PROBLEM

### Steps to Reproduce

use virtualbox

### Expected Behavior

i just want a button select

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by kgrubb** [comment] 2022-01-21 16:53
Closing as a duplicate of https://github.com/elementary/installer/issues/491. The linked issue has some more information on workarounds for installing in virtualbox.

**Closed by kgrubb** 2022-01-21 16:53 UTC
