### ISSUE TITLE
Can't connect to Wi-Fi

### ISSUE THREAD

**Issue by neelchauhan** [elementary/initial-setup#179] opened 2023-11-07 14:56 UTC
### What Happened?

I am unable to connect to Wi-Fi during the initial setup. I can connect to Wi-Fi after the initial setup fine.

### Steps to Reproduce

1. Install Elementary
2. When asked to connect to Wi-Fi, do so
3. You are unable to connect to Wi-Fi. Sometimes, the dash also quits.

### Expected Behavior

I should be able to connect to Wi-Fi during the initial setup when asked to.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

This happens on a HP Spectre x360 14 (13th Gen i7 with Intel AX211) and a Lenovo ThinkPad X1 Yoga (8th Gen i7 with AC8265).

**Comment by jlnr** [comment] 2023-11-07 15:47
I ran into the same issue: https://github.com/elementary/triage/issues/326

So presumably it is the same issue as https://github.com/elementary/greeter/issues/615, but maybe better to leave it open because the situation is slightly different (initial setup vs user switcher).

**Comment by danirabbit** [comment] 2023-11-07 17:06
Yes, this is a duplicate of #615. Initial Setup runs during a Greeter session :)

**Closed by danirabbit** 2023-11-07 17:06 UTC
