### ISSUE TITLE
Fresh Install: Must login twice

### ISSUE THREAD

**Issue by marbetschar** [elementary/initial-setup#128] opened 2021-12-01 08:40 UTC
### What Happened?

After doing a fresh install and completing the initial setup the user is presented with the login screen. For whatever reason I'm forced to log me in twice:

After entering the password for the first time, the screen flickers just briefly and presents the login screen again. Then I have to re-enter my password and hit login again. After the second attempt the desktop is presented.

This only happens the very first time after a fresh install - afterwards I never have to enter the password twice. Not sure if this happens for every user the first time, or just for the very first one on a clean system.

### Steps to Reproduce

1. Do a complete fresh install
2. Complete the initial setup wizard
3. Try to login with the newly created user - it will fail the very first time

### Expected Behavior

We should be able to login after the initial setup the very first time with the correct password and/or automatically login the user, since they already entered the correct password twice just before (see https://github.com/elementary/initial-setup/issues/50)

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Reproduced on bare metal twice (Dell XPS 7390 Dell XPS 9310) as well as in GNOME Boxes. So I guess this is not hardware related at all.

**Comment by cassidyjames** [comment] 2021-12-01 19:23
Duplicate of https://github.com/elementary/triage/issues/92

**Closed** 2021-12-01 19:24 UTC
Labels: Status: Duplicate
