### ISSUE TITLE
DataTime format is not applied in user session

### ISSUE THREAD

**Issue by ryonakano** [elementary/initial-setup#63] opened 2019-08-25 11:02 UTC
![Screenshot from 2019-08-25 10-03-18](https://user-images.githubusercontent.com/26003928/63648977-aaf6a200-c772-11e9-8ef8-6f158d9c4093.png)

Now Language is applied but DataTime format seems to be not applied to the user session depend on the language that users chose in Initial Setup. I selected Japanese but the format was not "Japan" but "US (English)".

![Screenshot from 2019-08-16 04-03-18](https://user-images.githubusercontent.com/26003928/63651411-63324380-c78f-11e9-83c1-811b599a6abb.png)

The timezone is also not applied correctly. I chose Japanese as a system language so I expect JST is set for timezone, but UTC is selected by default actually.

**Comment by danrabbit** [comment] 2019-08-25 22:14
I'm gonna close this as a duplicate of #35 since we don't currently attempt to set these

**Closed by danrabbit** 2019-08-25 22:14 UTC
